version: "3"
services:
    web:
      build: .
      ports:
        - "80:80"
      volumes:
        - ./sixth_app:/sixth_app
      environment:
        FLASK_ENV: development
    redis:
      image: "redis:alpine"