version: '3'

services:
  nginx:
    image: chaberb/nginx-ssl
    depends_on: 
      - flask
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  flask:
    image: chaberb/uwsgi-flask
    volumes:
      - ./app:/var/www/app
